//Header
export const TOGGLE_SEARCH ='TOGGLE_SEARCH'
export const FILTER_TYPES ='FILTER_TYPES'
export const BOOLEAN ='BOOLEAN'
export const CATEGORIES ='CATEGORIES'
export const HIDDEN_BED ='HIDDEN_BED'
export const HIDDEN_BATH ='HIDDEN_BATH'
export const HIDDEN_STORY ='HIDDEN_STORY'
export const HIDDEN_CATE ='HIDDEN_CATE'
export const BATH_ROOM ='BATH_ROOM'
export const BED_ROOM ='BED_ROOM'
export const STORY ='STORY'

//Content
	//Section B Filter navbar
export const B_TYPES ='B_TYPES'
export const B_CATE ='B_CATE'
export const B_STATUS ='B_STATUS'
export const B_CITY ='B_CITY'
export const B_AREA ='B_AREA'
export const B_DEFAULT ='B_DEFAULT'
export const TYPES_BOOL ='TYPES_BOOL'
export const CATE_BOOL ='CATE_BOOL'
export const STATUS_BOOL ='STATUS_BOOL'
export const CITY_BOOL ='CITY_BOOL'
export const AREA_BOOL ='AREA_BOOL'
export const DEFAULT_BOOL ='DEFAULT_BOOL'